server:
  port: 8762
#
#eureka:
#  instance:
#    hostname: peer2
#  client:
##    registerWithEureka: false
##    fetchRegistry: false
#    serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
##      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    